In [ ]:
import numpy as np
import pandas as pd

data_airbnb= pd.read_csv('Airbnb_Open_Data.csv', sep=',', error_bad_lines=False, index_col=False, dtype='unicode')

## PREPROCESSING DATA

In [19]:
data_airbnb.isnull().sum()
data_airbnb.a

(102599, 26)

In [4]:
#mengecek duplikasi data

data_airbnb.duplicated().value_counts()

False    102058
True        541
dtype: int64

In [20]:
#setelah dilakukan pengecekan duplikasi data. terdapat 541 yang mengandung duplikasi data, maka dilakukan penghapusan data.

data = data_airbnb.drop_duplicates(keep='first')

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102053,57365208,Cozy bright room near Prospect Park,77326652202,unconfirmed,Mariam,Brooklyn,Flatbush,40.64945,-73.96108,United States,...,NaN,7.0,12.0,3/27/2019,0.44,5.0,1.0,0.0,Shoes off Clean After yourself Turn Lights and...,NaN
102054,57365760,Private Bedroom with Amazing Rooftop View,45936254757,verified,Trey,Brooklyn,Bushwick,40.69872,-73.92718,United States,...,NaN,1.0,19.0,8/31/2017,0.72,3.0,2.0,0.0,#NAME?,NaN
102055,57366313,Pretty Brooklyn One-Bedroom for 2 to 4 people,23801060917,verified,Michael,Brooklyn,Bedford-Stuyvesant,40.67810,-73.90822,United States,...,NaN,2.0,50.0,6/26/2019,3.12,4.0,2.0,235.0,* Check out: 10am * We made an effort to keep ...,NaN
102056,57366865,Room & private bathroom in historic Harlem,15593031571,unconfirmed,Shireen,Manhattan,Harlem,40.81248,-73.94317,United States,...,NaN,2.0,0.0,NaN,NaN,1.0,1.0,0.0,Each of us is working and/or going to school a...,NaN
102057,57367417,Rosalee Stewart,93578954226,verified,Stanley,Manhattan,Harlem,40.81315,-73.94747,United States,...,NaN,4.0,22.0,6/15/2019,0.85,4.0,1.0,238.0,Please remember that this is a residential bui...,NaN

In [7]:
data.isnull().sum().sort_values(ascending=True)

#data.dropna(axis=1)

id                                     0
room type                              0
host id                                0
long                                   8
lat                                    8
neighbourhood                         16
neighbourhood group                   29
cancellation_policy                   76
instant_bookable                     105
country code                         131
number of reviews                    183
Construction year                    214
price                                247
NAME                                 250
service fee                          273
host_identity_verified               289
review rate number                   319
calculated host listings count       319
minimum nights                       400
host name                            404
availability 365                     448
country                              532
reviews per month                  15818
last review                        15832
house_rules                        51842
license                           102056
dtype: int64

In [15]:
columns = ['NAME','license','house_rules','country','country code','reviews per month','last review']
data_airbnb.dropna('columns', axis = 1, inplace = True)
data.info()

C:\Users\ASUS A44H\AppData\Local\Temp\ipykernel_3672\3753655259.py:2: FutureWarning: In a future version of pandas all arguments of DataFrame.dropna will be keyword-only.
  data_airbnb.dropna('columns', axis = 1, inplace = True)

TypeError: dropna() got multiple values for argument 'axis'

In [ ]:
null_values = data['host_identity_verified'].isnull().sum()
null_values.sort_values()

total_cells=np.product(data['host_identity_verified'].shape)

total_null=null_values.sum()

#Now we have to calculate the percentage of null values
pct_null = (total_null/total_cells) * 100 
print('Total null values is : {} %'.format(pct_null))

In [ ]:
data=data.dropna(subset=['neighbourhood','neighbourhood group'])
data.isnull().sum()
data.shape

In [ ]:
data['neighbourhood group'].value_counts()

In [ ]:
data.describe()

In [ ]:
data.dropna(thresh=(data.shape[0]* .9), axis=1, inplace=True)

data.info()

data.head()

In [ ]:
data.isnull().sum()

In [ ]:
data.describe()